spring.application.name=itensPregao

springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/swagger/index.html
server.servlet.context-path=/api

logging.level.root=DEBUG
server.port=${PORT:8080}